name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "dlnraja/com.tuya.zigbee"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
